name: simple_graphql
description: A simplified GraphQL controller
version: 2.3.0
repository: https://github.com/andrespd99/simple_graphql/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  graphql: ^5.1.2
  http: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0
