name: simple_graphql
description: A simplified GraphQL controller
version: 1.0.0+1
repository: https://github.com/andrespd99/simple_graphql/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  graphql: ^5.1.2
  meta: ^1.9.1
  mocktail: ^0.3.0

dependency_overrides:
  web_socket_channel: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.3
  very_good_analysis: ^5.0.0
