name: simple_graphql
description: A simplified GraphQL controller
version: 0.1.1+1
repository: https://github.com/andrespd99/simple_graphql/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
